name: Release Python Pkg (Poetry)

on:
  push:
    tags:
      - v*

jobs:
  release-py:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v6
        with:
          python-version: "3.13" # Debian 13
          cache: poetry
      - name: Install dependencies
        run: poetry install --no-interaction --no-root
      - name: Setup Poetry for PyPi
        run: poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}
      - name: Build package
        run: poetry build
      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: mpwrd-config
          path: dist/
      - name: Publish package
        run: poetry publish --no-interaction
